application: isb-cgc
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/spi/.*
  script: api.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: MySQLdb
  version: "latest"