application: striking-berm-771
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

handlers:
- url: /_ah/spi/.*
  script: api.APPLICATION